[from-internal]
exten => 101,1,Dial(PJSIP/101,30)
same => n,Hangup()

exten => 102,1,Dial(PJSIP/102,30)
same => n,Hangup()

; --- Enrutamiento para la Troncal (Interconexión con otra central) ---
exten => _9.,1,Dial(PJSIP/trunk-remote/${EXTEN:1},30)
same => n,Hangup()
