[from-internal]
exten => 101,1,Set(TIMEOUT(absolute)=900)
exten => 101,2,Dial(PJSIP/101,30)
exten => 101,3,Hangup()

exten => 102,1,Set(TIMEOUT(absolute)=900)
exten => 102,2,Dial(PJSIP/102,30)
exten => 102,3,Hangup()

exten => _9.,1,Dial(PJSIP/trunk-remote/${EXTEN:1},30)
exten => _9.,2,Hangup()
