[general]
dateformat=%F %T

[logfiles]
; Muestra eventos principales en la consola de Asterisk
console => notice,warning,error

; Guarda en /var/log/asterisk/messages todos los avisos y errores
messages => notice,warning,error

; Guarda un registro exhaustivo de señalización, llamadas y depuración
full => notice,warning,error,debug,verbose,dtmf,fax
